# Data Handling & Visualization 1 — Tabular data, Excel, and CSV

**Digital Foundation for Chemical Engineers**  \n
Duration: 60 minutes

## Today’s goal
Recognise tidy process data, understand the roles of Excel and CSV files, and start working with tables in Python. We will use the `pandas` library, a widely used tool for tabular data.

## 1. Why data management matters (10 min)

A plant may record thousands of sensor values, laboratory results, and batch records. Useful analysis depends on data being understandable and traceable.

### A tidy-table habit
- One **row** = one observation (for example, one hourly reading).
- One **column** = one variable (for example, temperature in °C).
- One **cell** = one value.
- Give columns meaningful names including units: `flow_m3_h`, not `Flow1`.

Excel is convenient for manual inspection; **CSV** is a plain-text table format that moves easily between Excel, Python, and reporting tools.

## 2. DataFrames: tables in Python (12 min)

A pandas **DataFrame** is like a spreadsheet table in Python. It has named columns and numbered rows. Run this cell; the first execution may take a moment while the library loads.

If `pandas` is unavailable in a new Codespace, run `pip install pandas` in the terminal, then restart the kernel.

In [11]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 20.4 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 36.1 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pandas as pd

process_data = pd.DataFrame({
    'hour': [8, 9, 10, 11, 12],
    'temperature_c': [72.1, 73.5, 75.2, 74.8, 76.0],
    'pressure_bar': [4.8, 4.9, 5.1, 5.0, 5.2],
    'flow_m3_h':  [12.0, 12.3, 11.9, 12.1, 12.4],
    'pH': [7.0, 7.1, 7.2, 7.3, 7.4]
})
process_data

   hour  temperature_c  pressure_bar  flow_m3_h   pH
0     8           72.1           4.8       12.0  7.0
1     9           73.5           4.9       12.3  7.1
2    10           75.2           5.1       11.9  7.2
3    11           74.8           5.0       12.1  7.3
4    12           76.0           5.2       12.4  7.4

**Run and modify (4 min):** Change a temperature value, rerun the cell, and observe the changed table. Add a `ph` column with five values.

**Challenge:** Create a second DataFrame for three batches with columns `batch_id`, `mass_kg`, and `yield_percent`.

## 3. Inspect before analysing (15 min)

Never jump directly to a conclusion from a new file. First inspect its size, column names, data types, and a few rows. `head()` gives the first rows; `info()` describes columns; `describe()` gives numerical summaries.

In [16]:
print('Shape (rows, columns):', process_data.shape)
print('\nColumn names:', list(process_data.columns))
display(process_data.head())
process_data.info()
display(process_data.describe())

Shape (rows, columns): (5, 5)

Column names: ['hour', 'temperature_c', 'pressure_bar', 'flow_m3_h', 'pH']

   hour  temperature_c  pressure_bar  flow_m3_h   pH
0     8           72.1           4.8       12.0  7.0
1     9           73.5           4.9       12.3  7.1
2    10           75.2           5.1       11.9  7.2
3    11           74.8           5.0       12.1  7.3
4    12           76.0           5.2       12.4  7.4

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   hour           5 non-null      int64
 1   temperature_c  5 non-null      float64
 2   pressure_bar   5 non-null      float64
 3   flow_m3_h      5 non-null      float64
 4   pH             5 non-null      float64
dtypes: float64(4), int64(1)
memory usage: 332.0 bytes

            hour  temperature_c  pressure_bar  flow_m3_h        pH
count   5.000000       5.000000      5.000000   5.000000  5.000000
mean   10.000000      74.320000      5.000000  12.140000  7.200000
std     1.581139       1.535252      0.158114   0.207364  0.158114
min     8.000000      72.100000      4.800000  11.900000  7.000000
25%     9.000000      73.500000      4.900000  12.000000  7.100000
50%    10.000000      74.800000      5.000000  12.100000  7.200000
75%    11.000000      75.200000      5.100000  12.300000  7.300000
max    12.000000      76.000000      5.200000  12.400000  7.400000

**Try it (5 min):** Answer from the output: How many readings are present? Which column has the highest average? Are all columns numerical?

**Challenge:** Use `process_data['temperature_c'].mean()` to calculate the mean directly, then format it to two decimals.

## 4. Excel and CSV: practical workflow (10 min)

A recommended workflow for this course:

1. Collect or export a controlled data table from a spreadsheet/system.
2. Save a working copy as **CSV UTF-8** with a clear file name and units in headers.
3. Import to Python, inspect it, clean it, then create repeatable outputs.
4. Keep the raw source unchanged; save cleaned data separately.

Avoid merged cells, decorative title rows, and mixed units in a single numeric column: they make reliable analysis harder.

## Pair task: design a data table (10 min)

You are recording hourly data from a heat exchanger. Propose five column names for time, inlet/outlet temperatures, flow, and a status note. Include units in appropriate names.

Then add a `delta_t_c` column below.

**Challenge:** Explain why storing `72 °C` as text is less useful than storing `72` in `temperature_c`.

In [31]:

process_data =  pd.DataFrame({
  'Time_hour': [8, 9, 10, 11, 12],
  'temperature_c_IN': [72.1, 73.5, 75.2, 74.8, 76.0],
  'temperature_c_OUT': [62.1, 63.5, 65.2, 64.8, 66.0],
  'flow_m3_h':  [12.0, 12.3, 11.9, 12.1, 12.4],
  'status':  ['OK', 'OK', 'OK', 'OK', 'OK']
   
})
process_data
process_data['delta_t_c'] = process_data['temperature_c_IN'] - process_data['temperature_c_OUT']
process_data

   Time_hour  temperature_c_IN  temperature_c_OUT  flow_m3_h status  delta_t_c
0          8              72.1               62.1       12.0     OK       10.0
1          9              73.5               63.5       12.3     OK       10.0
2         10              75.2               65.2       11.9     OK       10.0
3         11              74.8               64.8       12.1     OK       10.0
4         12              76.0               66.0       12.4     OK       10.0

## Exit check

You can distinguish Excel from CSV, explain tidy rows and columns, construct a DataFrame, and inspect a new table before trusting it. Next hour: import and export real CSV files.